#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "briefing"
name = "Briefing"
description.en = "Secure direct video group chat"
description.fr = "Chat vidéo direct sécurisé"

version = "3.1.11~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0"
website = "https://brie.fi/ng"
demo = "https://brie.fi/ng"
admindoc = "https://yunohost.org/packaging_apps"
code = "https://github.com/holtwick/briefing/"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/room"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/holtwick/briefing/archive/refs/tags/v3.1.11.tar.gz"
    sha256 = "04f64248ee9d93b59935ac9c78cbde739d6b6bac7f64f8739d36cccc2fd4646b"

    # autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
